---
name: 'Create cluster'
description: 'Create a Krucible Kubernetes cluster'
inputs:
  krucible-account-id:
    description: 'Krucible account ID'
    required: true
  krucible-api-key-id:
    description: 'Krucible API key ID'
    required: true
  krucible-api-key-secret:
    description: 'Krucible API key secret'
    required: true
  display-name:  # id of input
    description: 'Name of cluster'
    required: true
  duration:  # id of input
    description: 'Length of time in hours that the cluster should remain'
    required: true
    default: "1"
outputs:
  cluster-id:
    description: 'ID of the cluster created in Krucible'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    KRUCIBLE_ACCOUNTID: ${{ inputs.krucible-account-id }}
    KRUCIBLE_APIKEYID: ${{ inputs.krucible-api-key-id }}
    KRUCIBLE_APIKEYSECRET: ${{ inputs.krucible-api-key-secret }}
    CLUSTER_DURATION: ${{ inputs.duration }}
    CLUSTER_DISPLAY_NAME: ${{ inputs.display-name }}
  args:
    - create-cluster.sh
