---
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  create-and-test-cluster:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create a kubernetes cluster
      uses: "Krucible/krucible-github-action@master"
      id: create-cluster
      with:
        duration: 1
        display-name: github-test-cluster
        krucible-account-id: ${{ secrets.KRUCIBLEACCOUNTID }}
        krucible-api-key-id: ${{ secrets.KRUCIBLEAPIKEYID }}
        krucible-api-key-secret: ${{ secrets.KRUCIBLEAPIKEYSECRET }}

    - name: Run a kubectl command
      uses: "docker://bitnami/kubectl:1.18"
      id: run-kubectl
      with:
        args: 'get pods --all-namespaces'
